// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24Xp89UKesCe_a1OqNlECiH2gHOSZi2A',
    appId: '1:789137302123:web:31b535c9df8384a5c1472e',
    messagingSenderId: '789137302123',
    projectId: 'rvba-4bff0',
    authDomain: 'rvba-4bff0.firebaseapp.com',
    databaseURL: 'https://rvba-4bff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rvba-4bff0.appspot.com',
    measurementId: 'G-Z7SP930XT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICcucnbcD1rLzn0tKXikVvRm9_4AZbSE',
    appId: '1:789137302123:android:60ac4940a0fd4400c1472e',
    messagingSenderId: '789137302123',
    projectId: 'rvba-4bff0',
    databaseURL: 'https://rvba-4bff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rvba-4bff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0SMW0TpCCGVjG0tPA-HDDLBGJzXCykA',
    appId: '1:789137302123:ios:4fad86a34381b2bac1472e',
    messagingSenderId: '789137302123',
    projectId: 'rvba-4bff0',
    databaseURL: 'https://rvba-4bff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rvba-4bff0.appspot.com',
    iosBundleId: 'com.example.rvba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0SMW0TpCCGVjG0tPA-HDDLBGJzXCykA',
    appId: '1:789137302123:ios:4fad86a34381b2bac1472e',
    messagingSenderId: '789137302123',
    projectId: 'rvba-4bff0',
    databaseURL: 'https://rvba-4bff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rvba-4bff0.appspot.com',
    iosBundleId: 'com.example.rvba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24Xp89UKesCe_a1OqNlECiH2gHOSZi2A',
    appId: '1:789137302123:web:87789e191fd6c6c2c1472e',
    messagingSenderId: '789137302123',
    projectId: 'rvba-4bff0',
    authDomain: 'rvba-4bff0.firebaseapp.com',
    databaseURL: 'https://rvba-4bff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rvba-4bff0.appspot.com',
    measurementId: 'G-QK4CWFN32W',
  );
}
